### ISSUE TITLE
Why is this deprecated

### ISSUE THREAD

**Issue by SugoiDev** [PotterDai/RiderUnity3DConnector#3]
Hey, why is this deprecated?

I thought maybe it was part of the Unity3D rider integration plugin, but it seems it isn't.

**Comment by PotterDai** [comment]
Hey, thanks for asking.
The newest Unity3D rider plugin directly integrates Intellij's restful API to handle the communication.
Thus this connector is no longer needed.

**Comment by SugoiDev** [comment]
Ah, completely missed it! I was looking for a socks connection and ignored their restful call.

Thanks for the answer!
